/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#f0f0fb',
        'on-error-container': 'var(--color-on-error-container)',
        outline: '#737686',
        'on-background': '#191b23',
        'on-primary-container': '#003f46',
        'on-tertiary': 'var(--color-on-tertiary)',
        'surface-container-highest': '#e1e2ed',
        'error-container': 'var(--color-error-container)',
        'secondary-container': 'var(--color-secondary-container)',
        'on-primary': 'var(--color-on-primary)',
        'on-surface': '#191b23',
        'secondary-fixed': 'var(--color-secondary-fixed)',
        'on-secondary-fixed': 'var(--color-on-secondary-fixed)',
        'surface-container-low': '#f3f3fe',
        'primary-container': 'var(--color-primary-container)',
        background: '#faf8ff',
        'on-tertiary-fixed': '#360f00',
        'on-primary-fixed-variant': 'var(--color-on-primary-fixed-variant)',
        'inverse-surface': '#2e3039',
        tertiary: 'var(--color-tertiary)',
        'primary-fixed-dim': '#8dd8e4',
        'on-tertiary-fixed-variant': 'var(--color-on-tertiary-fixed-variant)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        'surface-tint': '#0053db',
        'tertiary-fixed': 'var(--color-tertiary-fixed)',
        'on-error': 'var(--color-on-error)',
        'inverse-primary': '#8dd8e4',
        surface: '#faf8ff',
        'secondary-fixed-dim': '#b7c8e1',
        'surface-container-high': '#e7e7f3',
        'surface-container': '#ededf9',
        'tertiary-fixed-dim': '#ffb596',
        'outline-variant': '#c3c6d7',
        'surface-bright': '#faf8ff',
        'surface-container-lowest': '#ffffff',
        primary: 'var(--color-primary)',
        'on-primary-fixed': '#003f46',
        'on-secondary-fixed-variant': '#38485d',
        error: 'var(--color-error)',
        'primary-fixed': 'var(--color-primary-fixed)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'surface-variant': '#e1e2ed',
        'on-tertiary-container': '#ffede6',
        'on-secondary': 'var(--color-on-secondary)',
        'surface-dim': '#d9d9e5',
        secondary: 'var(--color-secondary)',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'sidebar-collapsed': '64px',
        gutter: '16px',
        'container-margin': '24px',
        'sidebar-expanded': '240px',
        xl: '32px',
        base: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['11px', { lineHeight: '16px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'title-lg': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        display: ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
