/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#f0f0fb',
        'on-error-container': '#93000a',
        outline: '#737686',
        'on-background': '#191b23',
        'on-primary-container': '#eeefff',
        'on-tertiary': '#ffffff',
        'surface-container-highest': '#e1e2ed',
        'error-container': '#ffdad6',
        'secondary-container': '#d0e1fb',
        'on-primary': '#ffffff',
        'on-surface': '#191b23',
        'secondary-fixed': '#d3e4fe',
        'on-secondary-fixed': '#0b1c30',
        'surface-container-low': '#f3f3fe',
        'primary-container': '#2563eb',
        background: '#faf8ff',
        'on-tertiary-fixed': '#360f00',
        'on-primary-fixed-variant': '#003ea8',
        'inverse-surface': '#2e3039',
        tertiary: '#943700',
        'primary-fixed-dim': '#b4c5ff',
        'on-tertiary-fixed-variant': '#7d2d00',
        'on-secondary-container': '#54647a',
        'surface-tint': '#0053db',
        'tertiary-fixed': '#ffdbcd',
        'on-error': '#ffffff',
        'inverse-primary': '#b4c5ff',
        surface: '#faf8ff',
        'secondary-fixed-dim': '#b7c8e1',
        'surface-container-high': '#e7e7f3',
        'surface-container': '#ededf9',
        'tertiary-fixed-dim': '#ffb596',
        'outline-variant': '#c3c6d7',
        'surface-bright': '#faf8ff',
        'surface-container-lowest': '#ffffff',
        primary: '#004ac6',
        'on-primary-fixed': '#00174b',
        'on-secondary-fixed-variant': '#38485d',
        error: '#ba1a1a',
        'primary-fixed': '#dbe1ff',
        'tertiary-container': '#bc4800',
        'surface-variant': '#e1e2ed',
        'on-tertiary-container': '#ffede6',
        'on-secondary': '#ffffff',
        'surface-dim': '#d9d9e5',
        secondary: '#505f76',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'sidebar-collapsed': '64px',
        gutter: '16px',
        'container-margin': '24px',
        'sidebar-expanded': '240px',
        xl: '32px',
        base: '4px',
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['11px', { lineHeight: '16px', fontWeight: '600' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'title-lg': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        display: ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
